//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagpieUpdater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagpieUpdater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0} Updates....
        /// </summary>
        public static string DownloadingInstaller {
            get {
                return ResourceManager.GetString("DownloadingInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Now.
        /// </summary>
        public static string DownloadNow {
            get {
                return ResourceManager.GetString("DownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version.
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of {0} is available.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Updates Available.
        /// </summary>
        public static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by Magpie.
        /// </summary>
        public static string PoweredByMagpie {
            get {
                return ResourceManager.GetString("PoweredByMagpie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELEASE NOTES.
        /// </summary>
        public static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Me Later.
        /// </summary>
        public static string RemindMeLater {
            get {
                return ResourceManager.GetString("RemindMeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Installer.
        /// </summary>
        public static string RunInstaller {
            get {
                return ResourceManager.GetString("RunInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error verifying updater&apos;s signature. No updates will be installed..
        /// </summary>
        public static string SignatureErrorMsg {
            get {
                return ResourceManager.GetString("SignatureErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Signature Error.
        /// </summary>
        public static string SignatureErrorTitle {
            get {
                return ResourceManager.GetString("SignatureErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip This Version.
        /// </summary>
        public static string SkipThisVersion {
            get {
                return ResourceManager.GetString("SkipThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///	margin: 5px 10px;
        ///	padding: 5px 10px;
        ///	font-size: 1em;
        ///	font-family: &apos;Segoe UI&apos;, Verdana, sans;
        ///}
        ///
        ///.content {
        ///	color: #333;
        ///	font-size: 12px;
        ///	line-height: 1em;
        ///	margin: 0;
        ///	padding: 10px 15px;
        ///}
        ///
        ///a {
        ///	color: #356FBB;
        ///	text-decoration: initial;
        ///}
        ///
        ///a:hover { text-decoration: underline; }
        ///
        ///h1 {
        ///	font-size: 1.2em;
        ///	font-weight: 400;
        ///	color: #24a6a2;
        ///	margin-bottom: 10px;
        ///	margin-top: 0;
        ///}
        ///
        ///h1 + ul { margin-bottom: 20px; }
        ///
        ///h2 {
        ///	font-size: 1em;
        ///	font-weight: 400;
        ///	color: #35BBB7;
        ///	margin-bottom: 10px;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no updates available..
        /// </summary>
        public static string ThereAreNoUpdates {
            get {
                return ResourceManager.GetString("ThereAreNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Version.
        /// </summary>
        public static string YourVersion {
            get {
                return ResourceManager.GetString("YourVersion", resourceCulture);
            }
        }
    }
}
